### ISSUE TITLE
Can't seem to remove solc-select

### ISSUE THREAD

**Issue by nevillegrech** [crytic/solc-select#17]
Tried to install solc-select but it didn't quite work out for me so I'd like to remove it. Prior to installation I had solc installed using snap. I've removed the docker container, however when I try to install solc again using snap `sudo snap install solc` the command seems to be invoking solc-select instead:

```
mount: mounting /usr/bin on /workdir/usr/bin failed: Permission denied
mount: mounting /bin on /workdir/bin failed: Permission denied
mount: mounting /dev on /workdir/dev failed: Permission denied
mount: mounting /proc on /workdir/proc failed: Permission denied
mount: mounting /sys on /workdir/sys failed: Permission denied
chroot: can't execute 'chroot.sh': No such file or directory
```

I've also removed all files and folders that match `solc$` on this machine, but this still happens. I'm confused. In what ways is solc-select interacting with snap?

**Comment by ESultanik** [comment]
`solc-select` does not interact with snap at all. As is being tracked here, https://github.com/crytic/solc-select/issues/12#issuecomment-487049588, `solc-select` support for Linux is still experimental. Thus far, `solc-select` has only been thoroughly tested against the Homebrew package manager.

The error you are receiving is indicative that `solc-select` is still in fact installed, and for some reason it is being executed when you run `sudo snap install solc`. This may be a bug in `snap`, _e.g._, if it did not expect `solc` to be there.

What is the result of `which solc`? If that returns a path, make sure that that `solc` is deleted.

**Comment by nevillegrech** [comment]
Thanks. Indeed snap seems to be interacting with solc-select after removing the solc executable, which is weird. However the new version of solc-select you put up a few hours ago seems to be working fine for me now.

Please let me know if you find a clean way to remove solc-select on Ubuntu for future reference.

**Comment by nevillegrech** [comment]
Got to the root of the problem, it seems that solc-select's installation overwrote `/usr/bin/snap` with its own version of the `solc` script. I think all programs installed by snap are symlinks to `/usr/bin/snap`. I think the correct behavior of the installation in this case would have been to overwrite the symlink itself i.e. `/snap/bin/solc`.

**Comment by arcz** [comment]
This shouldn't be a problem anymore as we changed solc-select to be a Python package https://github.com/crytic/solc-select/releases/tag/0.2.0.
