### ISSUE TITLE
solc --upgrade will not work for source installation setup

### ISSUE THREAD

**Issue by montyly** [crytic/solc-select#18]
`solc --upgrade` is meant to update the list of available solc.

The current script pull the latest version on dockerhub:
https://github.com/crytic/solc-select/blob/c96e3e7a7bdd47738d4e133c0003b6ae14c13545/bin/solc#L4-L7

As a result, local changes (ex: using a branch) will be erased. 

I see two solutions:
1 - Update the [source installation documentation](https://github.com/crytic/solc-select#installation-from-source), to mention that update must be done through `docker build -t trailofbits/solc-select:latest .`
2 - Somehow detect that the installation is a git version, and switch the command accordingly 

I can submit a PR for solution 1, solution 2 seems more tricky.

Any thoughts?

**Comment by arcz** [comment]
This shouldn't happen anymore, see https://github.com/crytic/solc-select/releases/tag/0.2.0.
