### ISSUE TITLE
libreadline error when running solc

### ISSUE THREAD

**Issue by carumusan** [crytic/solc-select#21]
solc --version
Error loading shared library libreadline.so.8: No such file or directory (needed by /usr/bin/solc)
Error relocating /usr/bin/solc: unstifle_history: symbol not found
Error relocating /usr/bin/solc: rl_make_bare_keymap: symbol not found
Error relocating /usr/bin/solc: rl_bind_key_if_unbound_in_map: symbol not found
Error relocating /usr/bin/solc: rl_macro_dumper: symbol not found
Error relocating /usr/bin/solc: previous_history: symbol not found
Error relocating /usr/bin/solc: rl_vi_end_word: symbol not found
Error relocating /usr/bin/solc: rl_parse_and_bind: symbol not found
Error relocating /usr/bin/solc: rl_redisplay: symbol not found
Error relocating /usr/bin/solc: rl_push_macro_input: symbol not found
Error relocating /usr/bin/solc: rl_bind_key_in_map: symbol not found
Error relocating /usr/bin/solc: clear_history: symbol not found
Error relocating /usr/bin/solc: add_history: symbol not found
Error relocating /usr/bin/solc: rl_redraw_prompt_last_line: symbol not found
Error relocating /usr/bin/solc: rl_function_of_keyseq_len: symbol not found
Error relocating /usr/bin/solc: history_get: symbol not found
Error relocating /usr/bin/solc: rl_get_keymap: symbol not found
Error relocating /usr/bin/solc: rl_kill_text: symbol not found
Error relocating /usr/bin/solc: remove_history: symbol not found
Error relocating /usr/bin/solc: history_truncate_file: symbol not found
Error relocating /usr/bin/solc: rl_generic_bind: symbol not found
Error relocating /usr/bin/solc: rl_read_key: symbol not found
Error relocating /usr/bin/solc: read_history: symbol not found
Error relocating /usr/bin/solc: rl_add_defun: symbol not found
Error relocating /usr/bin/solc: history_expand: symbol not found
Error relocating /usr/bin/solc: rl_translate_keyseq: symbol not found
Error relocating /usr/bin/solc: rl_get_previous_history: symbol not found
Error relocating /usr/bin/solc: rl_forced_update_display: symbol not found
Error relocating /usr/bin/solc: rl_read_init_file: symbol not found
Error relocating /usr/bin/solc: rl_invoking_keyseqs: symbol not found
Error relocating /usr/bin/solc: append_history: symbol not found
Error relocating /usr/bin/solc: free_history_entry: symbol not found
Error relocating /usr/bin/solc: rl_unbind_key_in_map: symbol not found
Error relocating /usr/bin/solc: readline: symbol not found
Error relocating /usr/bin/solc: rl_variable_value: symbol not found
Error relocating /usr/bin/solc: history_set_pos: symbol not found
Error relocating /usr/bin/solc: rl_unbind_function_in_map: symbol not found
Error relocating /usr/bin/solc: read_history_range: symbol not found
Error relocating /usr/bin/solc: history_is_stifled: symbol not found
Error relocating /usr/bin/solc: stifle_history: symbol not found
Error relocating /usr/bin/solc: replace_history_entry: symbol not found
Error relocating /usr/bin/solc: rl_insert_text: symbol not found
Error relocating /usr/bin/solc: rl_get_keymap_by_name: symbol not found
Error relocating /usr/bin/solc: rl_set_screen_size: symbol not found
Error relocating /usr/bin/solc: rl_vi_bWord: symbol not found
Error relocating /usr/bin/solc: rl_get_termcap: symbol not found
Error relocating /usr/bin/solc: rl_ding: symbol not found
Error relocating /usr/bin/solc: where_history: symbol not found
Error relocating /usr/bin/solc: rl_delete_text: symbol not found
Error relocating /usr/bin/solc: rl_function_of_keyseq: symbol not found
Error relocating /usr/bin/solc: rl_bind_keyseq: symbol not found
Error relocating /usr/bin/solc: rl_reset_terminal: symbol not found
Error relocating /usr/bin/solc: history_tokenize: symbol not found
Error relocating /usr/bin/solc: rl_forward_word: symbol not found
Error relocating /usr/bin/solc: rl_function_dumper: symbol not found
Error relocating /usr/bin/solc: _rl_find_next_mbchar: symbol not found
Error relocating /usr/bin/solc: rl_vi_insertion_mode: symbol not found
Error relocating /usr/bin/solc: rl_variable_bind: symbol not found
Error relocating /usr/bin/solc: rl_named_function: symbol not found
Error relocating /usr/bin/solc: rl_initialize: symbol not found
Error relocating /usr/bin/solc: rl_vi_start_inserting: symbol not found
Error relocating /usr/bin/solc: rl_complete_internal: symbol not found
Error relocating /usr/bin/solc: history_list: symbol not found
Error relocating /usr/bin/solc: tilde_expand: symbol not found
Error relocating /usr/bin/solc: rl_funmap_names: symbol not found
Error relocating /usr/bin/solc: rl_set_keymap: symbol not found
Error relocating /usr/bin/solc: rl_variable_dumper: symbol not found
Error relocating /usr/bin/solc: rl_bind_keyseq_in_map: symbol not found
Error relocating /usr/bin/solc: write_history: symbol not found
Error relocating /usr/bin/solc: rl_on_new_line: symbol not found
Error relocating /usr/bin/solc: rl_clear_visible_line: symbol not found
Error relocating /usr/bin/solc: rl_completion_matches: symbol not found
Error relocating /usr/bin/solc: rl_completion_mode: symbol not found
Error relocating /usr/bin/solc: rl_add_undo: symbol not found
Error relocating /usr/bin/solc: rl_cleanup_after_signal: symbol not found
Error relocating /usr/bin/solc: rl_list_funmap_names: symbol not found
Error relocating /usr/bin/solc: using_history: symbol not found
Error relocating /usr/bin/solc: history_get_time: symbol not found
Error relocating /usr/bin/solc: remove_history_range: symbol not found
Error relocating /usr/bin/solc: rl_crlf: symbol not found
Error relocating /usr/bin/solc: rl_filename_completion_function: symbol not found
Error relocating /usr/bin/solc: rl_tilde_expand: symbol not found
Error relocating /usr/bin/solc: rl_newline: symbol not found
Error relocating /usr/bin/solc: rl_vi_editing_mode: symbol not found
Error relocating /usr/bin/solc: rl_username_completion_function: symbol not found
Error relocating /usr/bin/solc: rl_insert: symbol not found
Error relocating /usr/bin/solc: rl_tab_insert: symbol not found
Error relocating /usr/bin/solc: rl_menu_complete: symbol not found
Error relocating /usr/bin/solc: rl_yank_last_arg: symbol not found
Error relocating /usr/bin/solc: rl_complete: symbol not found
Error relocating /usr/bin/solc: history_length: symbol not found
Error relocating /usr/bin/solc: rl_completion_found_quote: symbol not found
Error relocating /usr/bin/solc: rl_completion_type: symbol not found
Error relocating /usr/bin/solc: rl_point: symbol not found
Error relocating /usr/bin/solc: history_lines_written_to_file: symbol not found
Error relocating /usr/bin/solc: history_max_entries: symbol not found
Error relocating /usr/bin/solc: history_write_timestamps: symbol not found
Error relocating /usr/bin/solc: rl_completion_suppress_quote: symbol not found
Error relocating /usr/bin/solc: rl_basic_word_break_characters: symbol not found
Error relocating /usr/bin/solc: rl_mark: symbol not found
Error relocating /usr/bin/solc: rl_directory_rewrite_hook: symbol not found
Error relocating /usr/bin/solc: rl_end: symbol not found
Error relocating /usr/bin/solc: rl_directory_completion_hook: symbol not found
Error relocating /usr/bin/solc: rl_completer_word_break_characters: symbol not found
Error relocating /usr/bin/solc: rl_dispatching: symbol not found
Error relocating /usr/bin/solc: rl_filename_quoting_desired: symbol not found
Error relocating /usr/bin/solc: history_search_delimiter_chars: symbol not found
Error relocating /usr/bin/solc: rl_executing_keyseq: symbol not found
Error relocating /usr/bin/solc: rl_key_sequence_length: symbol not found
Error relocating /usr/bin/solc: rl_filename_dequoting_function: symbol not found
Error relocating /usr/bin/solc: rl_filename_rewrite_hook: symbol not found
Error relocating /usr/bin/solc: rl_filename_stat_hook: symbol not found
Error relocating /usr/bin/solc: vi_insertion_keymap: symbol not found
Error relocating /usr/bin/solc: rl_prep_term_function: symbol not found
Error relocating /usr/bin/solc: rl_menu_completion_entry_function: symbol not found
Error relocating /usr/bin/solc: rl_attempted_completion_function: symbol not found
Error relocating /usr/bin/solc: history_comment_char: symbol not found
Error relocating /usr/bin/solc: rl_filename_completion_desired: symbol not found
Error relocating /usr/bin/solc: rl_done: symbol not found
Error relocating /usr/bin/solc: rl_completion_append_character: symbol not found
Error relocating /usr/bin/solc: rl_sort_completion_matches: symbol not found
Error relocating /usr/bin/solc: history_lines_read_from_file: symbol not found
Error relocating /usr/bin/solc: emacs_ctlx_keymap: symbol not found
Error relocating /usr/bin/solc: rl_deprep_term_function: symbol not found
Error relocating /usr/bin/solc: rl_editing_mode: symbol not found
Error relocating /usr/bin/solc: tilde_additional_prefixes: symbol not found
Error relocating /usr/bin/solc: history_subst_char: symbol not found
Error relocating /usr/bin/solc: rl_readline_state: symbol not found
Error relocating /usr/bin/solc: rl_attempted_completion_over: symbol not found
Error relocating /usr/bin/solc: vi_movement_keymap: symbol not found
Error relocating /usr/bin/solc: rl_filename_quote_characters: symbol not found
Error relocating /usr/bin/solc: rl_filename_quoting_function: symbol not found
Error relocating /usr/bin/solc: history_quotes_inhibit_expansion: symbol not found
Error relocating /usr/bin/solc: rl_readline_name: symbol not found
Error relocating /usr/bin/solc: rl_line_buffer: symbol not found
Error relocating /usr/bin/solc: emacs_meta_keymap: symbol not found
Error relocating /usr/bin/solc: rl_char_is_quoted_p: symbol not found
Error relocating /usr/bin/solc: rl_completion_entry_function: symbol not found
Error relocating /usr/bin/solc: rl_last_func: symbol not found
Error relocating /usr/bin/solc: rl_ignore_some_completions_function: symbol not found
Error relocating /usr/bin/solc: rl_completion_invoking_key: symbol not found
Error relocating /usr/bin/solc: rl_instream: symbol not found
Error relocating /usr/bin/solc: tilde_expansion_preexpansion_hook: symbol not found
Error relocating /usr/bin/solc: tilde_additional_suffixes: symbol not found
Error relocating /usr/bin/solc: rl_completion_suppress_append: symbol not found
Error relocating /usr/bin/solc: history_inhibit_expansion_function: symbol not found
Error relocating /usr/bin/solc: rl_completer_quote_characters: symbol not found
Error relocating /usr/bin/solc: rl_completion_quote_character: symbol not found
Error relocating /usr/bin/solc: history_base: symbol not found
Error relocating /usr/bin/solc: rl_terminal_name: symbol not found
Error relocating /usr/bin/solc: history_expansion_char: symbol not found
Error relocating /usr/bin/solc: rl_outstream: symbol not found
Error relocating /usr/bin/solc: emacs_standard_keymap: symbol not found
Error relocating /usr/bin/solc: rl_startup_hook: symbol not found
Error relocating /usr/bin/solc: history_quoting_state: symbol not found
Error relocating /usr/bin/solc: rl_signal_event_hook: symbol not found
Error relocating /usr/bin/solc: rl_special_prefixes: symbol not found
Error relocating /usr/bin/solc: rl_explicit_arg: symbol not found
Error relocating /usr/bin/solc: rl_num_chars_to_read: symbol not found
Error relocating /usr/bin/solc: rl_completion_mark_symlink_dirs: symbol not found

**Comment by n0thingness** [comment]
Same problem for me after having installed solc-select using

```
docker pull trailofbits/solc-select
export PREFIX=/usr/local
docker run --read-only -i --rm --entrypoint='/bin/sh' trailofbits/solc-select:latest -c 'cat /usr/bin/install.sh' | bash
```

**Comment by montyly** [comment]
Hi,

Thank you @carumusan and @n0thingness for reporting the issue. 

What OS are you using?

**Comment by n0thingness** [comment]
ProductName:	         Mac OS X
ProductVersion:	10.14.6
BuildVersion:	        18G84

**Comment by carumusan** [comment]
Also MacOS and had the same problem as @n0thingness with /usr/bin/solc not being allowed.

This may be an upstream issue with ethereum/solc.

**Comment by arcz** [comment]
This shouldn't happen anymore, see https://github.com/crytic/solc-select/releases/tag/0.2.0.
