### ISSUE TITLE
Unsupported solidity 0.6.12 in docker environment

### ISSUE THREAD

**Issue by apalepu23** [crytic/solc-select#31]
I'm attempting to use the docker set up for echidna, and i am unable to sol-select solidity 0.6.12. It tells me that the max available version number is 0.6.9. Thanks!

**Comment by disconnect3d** [comment]
The current version has solc 0.6.12; though it is still outdated, which we will fix today.
![image](https://user-images.githubusercontent.com/10009354/102781736-7c093400-4398-11eb-813e-8d560f801614.png)
