### ISSUE TITLE
switch to the expected solc version automatically

### ISSUE THREAD

**Issue by abialy** [crytic/solc-select#32]
I am using docker slighter and trying to use solc-select automatically. How it should be configured? 

Currently it does not work even if I specify multiple versions using --solc-solcs-select

Any help would be appreciated.

**Comment by disconnect3d** [comment]
I think this issue is quite outdated: we now migrated solc-select to a Python version installed with `pip`.

Please create a new issue if the problem persists for you or if there is something we could improve in the new version.
