### ISSUE TITLE
Persistent contract files

### ISSUE THREAD

**Issue by iphelix** [crytic/solc-select#35]
Solidity files appear to persist within the docker image between runs, so any changes on the local disk do no affect what dockerized compiler actually processes after the first time. Restarting Docker helps fix the issue.

**Comment by montyly** [comment]
Hi @iphelix .

Thank you for reporting this. It's an issue we actually recently realized, and we are investigating a potential fix

**Comment by iphelix** [comment]
Fantastic, I'm glad that you can also replicate this.

**Comment by NatalieChin80** [comment]
Hi @iphelix, 

#38 is a python-rewrite of `solc-select` that uses native Mac OS binaries (removing the need of Docker). It was just recently merged. You can clone the repository/pull the most recent changes and add the directory to your path. Then, you can run `solc-select install 0.7.0 0.8.0` for example, to install these versions.

The linked PR (#38) has additional examples on how to use the new `solc-select`. Additional documentation should be coming out soon. Feel free to give it a try and let us know if you have any questions!

**Comment by arcz** [comment]
This shouldn't happen anymore, see https://github.com/crytic/solc-select/releases/tag/0.2.0.
