### ISSUE TITLE
"use" is not found. in Linux

### ISSUE THREAD

**Issue by M-Hammad-Ali** [crytic/solc-select#39]
I have followed the given procedure but when try to use `solc use 0.5.6` it gives `"use" is not found`

![image](https://user-images.githubusercontent.com/55716079/103776431-41b6bc80-5051-11eb-9b58-4e3bee62156e.png)

**Comment by eerkaijun** [comment]
I am facing the same issue

**Comment by arcz** [comment]
This shouldn't happen anymore, see https://github.com/crytic/solc-select/releases/tag/0.2.0.
