### ISSUE TITLE
Lost support for solc < 0.4.10

### ISSUE THREAD

**Issue by montyly** [crytic/solc-select#41]
With the new python refactoring, we lost the support for solc < 0.4.10

We are now using https://binaries.soliditylang.org/, which does not list versions that are too old, while in the past we used:
https://github.com/crytic/solc-select/blob/8a0ba47c99ce75c11eecde7ad6bbfed52d072d05/scripts/install_solc.sh#L5

Alternatively, we could get the missing binaries from: https://github.com/crytic/solc

**Comment by NatalieChin80** [comment]
Merged with #53
