### ISSUE TITLE
mac doesnt work

### ISSUE THREAD

**Issue by jjhesk** [crytic/solc-select#42]
After I install the package completely in macosx 11.1 Beta and i restart the terminal for entering the `solc-select` and it doesn't find the command again. Now the only currently working way is installing the package on centos and they works without any workaround at all.

**Comment by xlab** [comment]
```
 solc select 0.6.6
chroot: can't execute 'chroot.sh': No such file or directory
```

bigSur 11.0.1

**Comment by ESultanik** [comment]
You don't even need to `git clone` the repository. You should just be able to run `pip3 install solc-select` from anywhere on any system with a valid Python 3.* install.

**Comment by 0xicingdeath** [comment]
I've been unable to reproduce this issue on OS X with the python version of solc-select. Please create a new issue if the problem persists with the [latest stable release](https://github.com/crytic/solc-select/releases/tag/0.2.1). Thanks!
