### ISSUE TITLE
Unsupported platform

### ISSUE THREAD

**Issue by glazec** [crytic/solc-select#43]
I am using Win10. When I run `solc-select install`, it returns `Available versions to install:
Unsupported platform.`

**Comment by rmi7** [comment]
Sorry, (at this time) Windows is not supported.

https://github.com/crytic/solc-select/blob/d866c55b7d78f421a7724d7b7d723bd8bedef28b/solc_select/solc_select.py#L85-L93

**Comment by glazec** [comment]
I notice that solc has windows binary support. Do you plan to support windows in the near future?

**Comment by montyly** [comment]
Hi @glazec, thanks for pointing this out.

We will add the support for `windows-amd64` soon

**Comment by glazec** [comment]
That's awesome! I look forward to using it on my windows PC.

**Comment by appswarehouse** [comment]
is there any plan to add it anytime soon, because this issue still keep occuring

**Comment by NatalieChin80** [comment]
Hey @appswarehouse, thanks for reaching out! Yep, we are currently working on Windows support, which can be tracked in #54.

**Comment by 0xicingdeath** [comment]
Hey @glazec and @appswarehouse, we have a beta version for Windows support for v0.4.5 to latest. Feel free to run the following to test it out:

```
git clone https://github.com/crytic/solc-select.git
cd solc-select
git checkout add/windows-support
python3 setup.py install 
solc-select install <version>
solc-select use <version> 
```

Happy to help any problems you encounter or feedback. Thanks!
