### ISSUE TITLE
Solc version not being switched

### ISSUE THREAD

**Issue by aram10** [crytic/solc-select#47]
I am attempting to switch my solc version from 0.8.3 to 0.4.24, but this does not seem to be working as shown when I check the version, and when I try and build contracts using 0.4.24.
![solc](https://user-images.githubusercontent.com/59741191/112201051-40c01080-8be6-11eb-9b72-b369c0eb9ed7.PNG)

**Comment by montyly** [comment]
Hi @aram10,

This might be a conflict in your PATH, where multiple `solc` executables exist. Can you run `whereis solc`?

**Comment by aram10** [comment]
Ah yes, I believe you're correct. Here is the output:

`solc: /usr/bin/solc /usr/local/bin/solc `/home/alex/.local/bin/solc`

How would I remedy this?

**Comment by montyly** [comment]
Can you share the output of `whereis solc-select` ?

**Comment by Azuryte** [comment]
Not working for me as well. I'm on macos.

which solc:
/opt/homebrew/bin/solc

which solc-select:
/Library/Frameworks/Python.framework/Versions/3.9/bin/solc-select

What can I do about this?

**Comment by NatalieChin80** [comment]
Hey @aram10! Are you still experiencing this? Can you share the output of `which solc`? 

Hey @Azuryte! You should not need the homebrew installed `solc` as `solc-select` will download the Mac OSX binaries you need to execute. Can you try running `brew uninstall solidity`?

**Comment by Azuryte** [comment]
> Hey @aram10! Are you still experiencing this? Can you share the output of `which solc`?
> 
> Hey @Azuryte! You should not need the homebrew installed `solc` as `solc-select` will download the Mac OSX binaries you need to execute. Can you try running `brew uninstall solidity`?

Yeah, that makes total sense. It's working. Thanks!

**Comment by 0xicingdeath** [comment]
This issue is caused by a duplicate installation of `solc` on a machine and binaries that are downloaded from `solc-select`. Uninstalling the secondary solc installation should allow `solc-select` to recognize the binaries. Please create a new issue if the problem still persists. Thanks!

**Comment by PatrickAlphaC** [comment]
Can we add this to the FAQ? For MacOS specifically?
