### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by taylorgag** [crytic/solc-select#52]
Sorry to bother you. Why I use the command "pip3 install solc-select" and then use "solc-select install 0.8.1 ",it shows "solc-select: not found"

**Comment by NatalieChin80** [comment]
Hey @taylorgag. Thanks for reporting this. What OS and version are you using?

**Comment by taylorgag** [comment]
> Hey @taylorgag. Thanks for reporting this. What OS and version are you using?
Well, I think I have solved this problem,it was not your fault.

**Comment by rodriguesnavil** [comment]
I had the same problem, the issue was with user packages not being discovered. The answer helped me resolve the issue
https://stackoverflow.com/a/62151306/5594598
